name: "C/C++ CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: "Install ceedling"
      run: sudo gem install ceedling
    - name: "Add ceedling to path"
      run: export PATH="$PATH:~/.gem/ruby/2.5.0/bin"
    - name: "Make libs"
      run: make -C ft_printf
    - name: "Run Ceedling unit-tests"
      run: ceedling test
    - name: "Install norminette"
      run: |
        sudo apt-get install ruby ruby-bundler ruby-dev build-essential
        git clone https://github.com/42Paris/norminette.git ~/.norminette/
        cd ~/.norminette/
        bundle
        echo 'alias norminette="~/.norminette/norminette.rb"' >> ~/.bashrc
        source ~/.bashrc
        cd ~/Corewar
    - name: "Run norminette tests"
      run: |
        norminette src/* includes/* 
        ft_printf/src* ft_printf/includes/*   
        ft_printf/libft/src* ft_printf/libft/includes/*
