name: "C/C++ CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-10.15]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

      # Library compilation:
    - name: "Compile libftpribtf library"
      run: make

      # Unit-testing:
    - name: "Install ceedling"
      run: sudo gem install ceedling
    - name: "Add Ceedling to PATH"
      run: export PATH="$PATH:~/.gem/ruby/2.5.0/bin"
    - name: "Run unit-tests"
      run: make unit-test

      # Functional testing and leaks-check:
    - name: "Install valgrind"
      run: sudo apt-get install valgrind
    - name: "Run functional tests and check leaks"
      run: make memcheck
    - name: "Show logs' tails"
      run: tail logs/leaks/*

    - name: "Install norminette"
      run: |
        sudo apt-get install ruby ruby-bundler ruby-dev build-essential
        git clone https://github.com/42Paris/norminette.git ~/.norminette/
        cd ~/.norminette/
        bundle
    - name: "Run norminette tests"
      run: make norm
